### ISSUE TITLE
如何配置？

### ISSUE THREAD

**Issue by woshiccm** [Hanseltu/kaleidoscope-tutorial#1]
我用VS打开，但是会有这种'llvm/Bitcode/ReaderWriter.h' file not found问题，请问怎么配置呢，我brew install llvm了，可否加个微信请教一下？

**Comment by Hanseltu** [comment]
你好，原因可能是因为找不到你电脑中llvm的头文件位置。

你安装好llvm后可以先执行 `llvm-config --cxxflags --system-libs --libs` 看一下llvm include 文件位置，然后在项目CMakeLists.txt文件中替换一下你的路径，一般就可以了。

单个文件执行可以用 

```
clang++ -g -O3 chapter2-Implementing-a-Parser-and-AST.cpp `llvm-config --cxxflags --system-libs --libs`
``` 

看看能否执行成功。

如果还有问题，欢迎加我微信讨论~

**Comment by woshiccm** [comment]
这样用Cmake编译可能没问题，但是你用的什么编译器呢？我用VS，然后头文件还是找不到
![屏幕快照 2020-03-07 下午11.17.47.png](https://upload-images.jianshu.io/upload_images/2086987-b2c9e33af267b6cb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Hanseltu** [comment]
我用的是Mac默认的clang，我没用VC编译过，VC应该会找不到llvm相关的库，建议换个编译器试一下

```
tuhaoxin@MacBook-Pro kaleidoscope % clang++ --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by woshiccm** [comment]
我也是用的Mac默认的clang，那你用的啥编辑器呢？

**Comment by Hanseltu** [comment]
编辑器用的CLion，单个文件可以执行成功吗？像这样

```
clang++ -g -O3 chapter2-Implementing-a-Parser-and-AST.cpp `llvm-config --cxxflags --system-libs --libs`
```

**Comment by woshiccm** [comment]
应该是可以的吧，还没尝试，过会试试，CLion通过进行配置然后可以找到头文件的吗？刚开始写C++，一脸懵逼中

**Comment by woshiccm** [comment]
用xcode进行配置是可以，但是看很多使用LLVM开发的项目都没有xcodeproj

**Comment by Hanseltu** [comment]
对的，我项目下clion-project/kaleidoscope 就是整个CLion项目，我这里可以成功运行。不过和编辑器关系应该不大，保证 `llvm-config --cxxflags --system-libs --libs`成功执行和编译器clang应该就可以。

**Comment by woshiccm** [comment]
好的 谢谢哈
