### ISSUE TITLE
can not access the pages

### ISSUE THREAD

**Issue by duchao713** [Hanseltu/kaleidoscope-tutorial#2]
Hi Tu,

试了一下，所有页面都访问不了了。是临时的问题还是永久性的？

谢谢。

**Comment by Hanseltu** [comment]
Hi.

由于阿里云服务器到期且不能再续费，目前还没部署到新的网站，预计本周末更新好。

谢谢~

**Comment by Hanseltu** [comment]
hi @duchao713.

链接已恢复访问，谢谢支持~

**Comment by duchao713** [comment]
可以访问了，谢谢！
